### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by gottagofaster236** [SPEEPSHighway/SADX-cutscene-decompilation#1]
Just looking at the code, I noticed that the `case 2:` labels inside the `switch (state)` statements (that are supposed for cleanup) always free null pointers. For example:

https://github.com/SPEEPSHighway/SADX-cutscene-decompilation/blob/0207de5d08f325365d1412853e3866370e99e7b8/SADX-cutscene-decompilation/Tails/ev0030_t_intro.cpp#L6-L14
https://github.com/SPEEPSHighway/SADX-cutscene-decompilation/blob/0207de5d08f325365d1412853e3866370e99e7b8/SADX-cutscene-decompilation/Tails/ev0030_t_intro.cpp#L329-L348

(Since every time the function is called, the local variables are recreated).

**Comment by SPEEPSHighway** [comment]
Thanks for telling me this. I'll go through and fix everything now.

**Comment by gottagofaster236** [comment]
Closing the issue since it's been fixed with 8af82c51b3024cc833b9994b822c4b99115881c1.
